services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wmsucms_web

    env_file:
      - ./dbvar.env   # Ensure this file is in the same dir as docker-compose.yml
    volumes:
      - ./your-web-code:/var/www/html
      - ./aiven-certs/ca.pem:/etc/ssl/aiven/ca.pem

    restart: unless-stopped
